### ISSUE TITLE
Return Hash Before Uploading to Cloud

### ISSUE THREAD

**Issue by super3** [StorjOld/MetaDisk#1]
Noticed that the file is uploaded very quickly to the server, but takes quite a long time to be uploaded to the other filehosts. We should change the logic so that the file is  available for download off the local node as soon as the file is uploaded.

**Comment by hugopeixoto** [comment]
This is fixed in the latest versions of web-core and BitCumulus.

Now each web request is only responsible for uploading the file,
and there's a daemon to sweep the database and upload
new files to the filehosts.
