### ISSUE TITLE
Implement 'Tweet for Space'

### ISSUE THREAD

**Issue by super3** [StorjOld/MetaDisk#28]
We currently have this in our "free storage" section. Need to have some code that allows a user to post a tweet, and then return them to the node for a reward. Need to make sure the user can't cheat the system with fake callbacks. 

![http://i.imgur.com/SXkSdeR.png](http://i.imgur.com/SXkSdeR.png)

**Comment by hugopeixoto** [comment]
This should be implemented as a separate web application.
After validating the tweet, the app should increment the user account's balance.
This can be done through the following API:
- https://github.com/Storj/web-core#private-api-requires-authentication

**Comment by super3** [comment]
Twitter Button: https://about.twitter.com/resources/buttons#tweet

**Comment by super3** [comment]
Some information on callback: https://stackoverflow.com/questions/4947825/is-there-a-callback-for-twitters-tweet-button

**Comment by EmergentBehavior** [comment]
I've been going back-and-forth with @super3 and am working on this. Twitter allows for callbacks after user actions via web intents.

After updating the tweet link...

```
<a href="https://twitter.com/intent/tweet?url=http%3A%2F%2Fnode2.storj.io&amp;text=%23storj%20is%20revolutionizing%20cloud%20storage.%20Learn%20more%20at%20storj.io" class="btn btn-primary btn-block">
```

...you can add the following JS at the bottom of the page:

```
window.twttr = (function (d,s,id) {
          var t, js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return; js=d.createElement(s); js.id=id;
          js.src="https://platform.twitter.com/widgets.js"; fjs.parentNode.insertBefore(js, fjs);
          return window.twttr || (t = { _e: [], ready: function(f){ t._e.push(f) } });
        }(document, "script", "twitter-wjs"));
        twttr.ready(function (twttr) {
            twttr.events.bind('tweet', function (event) { 
                console.log('Tweeted!'); 
            });
        });
```

The catch here is that if you run a callback after a user tweets, Twitter won't let you see any information about them. However, if you bind to 'follow' instead of 'tweet', `event.data` will contain relevant identifying information.

Would we be satisfied with the simpler tweet callback? If so, I can write up a bit of python to handle data sent from the front-end (e.g. tokens) and add the 5G of space.

**Comment by super3** [comment]
Ideally the Twitter module will be given a cache of tokens for ~5GB of bandwidth. If it receives a callback then it can simply do an API call to the node to add the space. The simpler method should be fine for now. 

I see two problems with this in scale in the future when people try to game the system:
1) Invalid Callbacks
2) Dummy Twitter accounts

This would have to be solved with rate limiting, and perhaps server side verification of the tweets and accounts. Hopefully we won't have to ever get to that point.

**Comment by EmergentBehavior** [comment]
If you want more protection, we can do the following:
(a) Use the streaming API and scan for new instances of the tweet. This could tie into rate limiting, as you mentioned.
(b) Use Twitter's REST API/auth system to have the user specifically grant us the permission to know their handle.

I'll move forward with the simple method in the meantime, but can add (a) or (b) down the road as needed.

**Comment by super3** [comment]
Probably just leave a spec up for later implementation if the problem arises. I think perhaps both would be needed. Could have a positive feature from the whole thing. The more followers a user has, the more free bandwidth credits they get.

**Comment by EmergentBehavior** [comment]
Finished the front-end code earlier this evening (it's integrated into a local copy of main.js). Have been writing up the Flask app, but Twitter isn't producing access tokens properly at the moment so I can't test the generated tweetkey (to ensure they actually tweeted). Will try again tomorrow.

**Comment by EmergentBehavior** [comment]
After playing with the (now working) streaming Twitter API, I found it just too slow to do a good job. Now, I am using OAuth instead to get permission from the user and then posting a Tweet on their behalf. Here is the new flow I'm working on:

(1) Clicking "Tweet" button generates a request token from the Flask app, which is incorporated into an authorization url/popup for the user.
(2) Once the user authorizes our Twitter app, we receive access key/token from them that allows us to post via their account.
(3) Before we post, we check a MongoDB collection to ensure they haven't already received 5 GB of space.
(4) We use their access credentials to post the tweet, then discard immediately afterwards (should make all this clear on the site).
(5) After a successful tweet, we use the Storj coupon API to redeem a 5GB coupon. These coupons can be retrieved from a separate MongoDB collection and marked inactive after successful use.
(6) If space added successfully, their Twitter handle is added to the first MongoDB collection and marked as activated.

Finished (1), working on the rest now.

This is all taking longer than I initially planned, but this latest solution is by far the most robust.

EDIT: replaced Redis with MongoDB

**Comment by EmergentBehavior** [comment]
This should be ready to go with MongoDB. If I receive some more info about our Postgres setup I can reconfigure it for that.

**Comment by super3** [comment]
Removing for from the milestone and the UI until it can get implemented.
