### ISSUE TITLE
Token Spec

### ISSUE THREAD

**Issue by super3** [StorjOld/MetaDisk#30]
We want users to be able to buy bandwidth from a node. In keeping with our policies regarding privacy and security we really don't want usernames and passwords. Instead we use a 16 digit alphanumeric token. This token is automatically generated on the node/server side. All tokens should be hashed in the database.
## Public API
- **/api/token/new** - Generate and returns a random token. Before returning the token, we double check for the infinitesimally small chance that we have a collision. 
- **/api/token/balance/&lt;token&gt;** - Return a JSON string that gives the current gigabyte balance of the token.
- **/api/token/prices** - Return a JSON string that gives the current price the node is selling bandwidth for.
## Private API
- consume(token, gigabytes) - Subtract the gigabytes from the user's token.
- can_consume(token, gigabytes) - Makes sure there is enough gigabytes to complete the current action.
- add(token, gigabytes) - Adds gigabytes to the user's token.

**Comment by hugopeixoto** [comment]
The API is now implemented in web-core's master.
