### ISSUE TITLE
Implement 'Buy Space'

### ISSUE THREAD

**Issue by super3** [StorjOld/MetaDisk#35]
We currently have a 'Buy Space' button, and modal in the 'Your Account' module. This needs to be implemented with [Coinbase API's](https://coinbase.com/docs/api/overview). 

![http://i.imgur.com/fwZkeIY.png](http://i.imgur.com/fwZkeIY.png)

**Comment by hugopeixoto** [comment]
You can get the price list by querying `/api/token/prices`

After validating the purchase, the app should increment the user account's balance.
This can be done through the following API:
- https://github.com/Storj/web-core#private-api-requires-authentication

**Comment by super3** [comment]
@boshevski We worked on Coinbase integration before for the Primecoin website. Do you think we could use or port that script to work for Metadisk?

**Comment by EmergentBehavior** [comment]
What still needs to be done on this issue?

**Comment by super3** [comment]
Created #56 and #57
