### ISSUE TITLE
Implement 'Edit' for Access Token 

### ISSUE THREAD

**Issue by super3** [StorjOld/MetaDisk#44]
There are two options for this:

1) The user is able to temporarily edit the text box. When they are done we reload their bandwidth numbers. 
2) We open a modal where they can enter their old access token, after they hit ok we reload their bandwidth numbers.

![https://i.imgur.com/kuLUJXQ.png](https://i.imgur.com/kuLUJXQ.png)

**Comment by EmergentBehavior** [comment]
I implemented (1) as it's cleaner. After hitting edit, the token field is editable. It becomes disabled again when it loses focus or the user presses enter. Numbers update accordingly.
