### ISSUE TITLE
Increase Free Space to 1GB

### ISSUE THREAD

**Issue by super3** [StorjOld/MetaDisk#47]
![https://i.imgur.com/bNPVUQP.png](https://i.imgur.com/bNPVUQP.png)

**Comment by EmergentBehavior** [comment]
This is trivial to change on the front-end Metadisk side. I took a look at web-core's token manager and I think it's just a matter of associating the right promotion size to the 'PLEASE' promocode in our existing databases.

**Comment by super3** [comment]
@hugopeixoto was typically responsible for that. Want me to give you server access to make the DB change?

**Comment by EmergentBehavior** [comment]
Sure.

**Comment by EmergentBehavior** [comment]
Commit 21776a8 fixed this. Also updated db to reflect higher byte size for PLEASE promo code. Please test.
