### ISSUE TITLE
Growl on Button Press

### ISSUE THREAD

**Issue by super3** [StorjOld/MetaDisk#50]
![https://i.imgur.com/ZTwLA1z.png](https://i.imgur.com/ZTwLA1z.png)
Both buttons should trigger a growl. They both modify the space, but that is hidden behind the modal so the user has no idea whats going on in the background.

**Comment by EmergentBehavior** [comment]
Added some growl messaging ,etc. However, API is throwing back 403 forbidden errors behind the scenes...

**Comment by super3** [comment]
Yeah I tried the 2nd promo code and it didn't do a success growl. Might want to check for errors on the API side.
