### ISSUE TITLE
Bring Node 1 Up to Date with Codebase

### ISSUE THREAD

**Issue by super3** [StorjOld/MetaDisk#54]

**Comment by EmergentBehavior** [comment]
This should probably be moved to web-core. Also, right now node2 is hard-coded into one of the deploy scripts:
https://github.com/Storj/lunchbox/blob/master/chef/site-cookbooks/storj/recipes/metadisk.rb#L8

This would need to be changed before deploying on node1 or metadisk wouldn't function properly.

**Comment by EmergentBehavior** [comment]
node1 should be up-to-date (as of now), though I had to change a hard-coded reference to node2 in main.js to node1. Should try testing.

**Comment by EmergentBehavior** [comment]
Database tables are out of date. Better to just rebuild this node once we stabilize node2.
