### ISSUE TITLE
Correct Space from Buy

### ISSUE THREAD

**Issue by super3** [StorjOld/MetaDisk#57]
Should give them only 100 GB of bandwidth.

**Comment by EmergentBehavior** [comment]
Can we confirm the coinbase callback has the correct number of bytes?

**Comment by EmergentBehavior** [comment]
This might have been a web-core issue. Coinbase repeatedly hits the callback function unless it receives the proper response code. We had 201 but it expected 200. Commit https://github.com/Storj/web-core/commit/d8140b844505 in web-core fixes that but it should be tested.

**Comment by super3** [comment]
Seems to be fixed.
