### ISSUE TITLE
General Bandwidth Errors

### ISSUE THREAD

**Issue by super3** [StorjOld/MetaDisk#59]
Seeing tons of problems with the token system. Able to download and upload files over my bandwidth limits.

**Comment by super3** [comment]
@EmergentBehavior Do you think you can look into this? I want to let people try out Metadisk, but this issue keep popping up randomly.

**Comment by EmergentBehavior** [comment]
It should return 'balance insufficient' in the response if you're out of space. I tested this a while back and it seemed to work.

See: https://github.com/Storj/web-core/blob/master/index.py#L65

Can you give me steps to reproduce? Is there anything in the console? Is the front-end adding file to the uploads list that weren't actually uploaded?
