### ISSUE TITLE
Insufficient balance on node1?

### ISSUE THREAD

**Issue by pryds** [StorjOld/MetaDisk#64]
On node1, which is supposed to have unlimited bandwidth, I get a "Whoops! We were unable to download your file due to an insufficient balance." when trying to download a small PDF that I uploaded there:
http://node1.metadisk.org/api/download/815209a0362df177a63690cacdbfcd0ddf89f380e369a6339073d09b72d913c2?key=97d24ca5fbea08ef1d5f05a1da4ef81b9c638a62ff7f1a008f6a7e7db4852918&token=fOwvOPaCiw0qFZm1
This is the Satoshi whitepaper, so not a large file at all. Happens when up- and downloading from both Firefox and Chromium. I've put a series of txt files there, also, which download fine.

Other PDFs seem fine, too. Just this one Satoshi PDF (downloaded directly from bitcoin.org)

**Comment by EmergentBehavior** [comment]
This is actually a web-core issue as the API returns a 500 error. The Metadisk repo is for front-end issues (for this branch and `ember`). Moving issue.

**Comment by super3** [comment]
@EmergentBehavior where did you put this issue?

**Comment by EmergentBehavior** [comment]
You closed it:
https://github.com/Storj/web-core/issues/13
